version: '3.8'
services:
  vbackup:
    image: hantbk/vbackup:latest
    container_name: vbackup
    restart: always
    volumes:
      - /data:/data
      - /data/vbackup:/root/.vbackup
    ports:
      - "8012:8012"
    user: "root"
    hostname: ${HOSTNAME}