name: Build & Test
on:
  pull_request:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...